# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character"""

[character]
format = '\$ '

[directory]
truncate_to_repo = false
style = 'bold #a9dc76'

[git_branch]
symbol = ''
format = '[$symbol $branch(:$remote_branch)]($style) '
style = 'bold #78dce8'

[git_commit]
style = 'bold #a9dc76'

[git_state]
style = 'bold #ffd866'

[git_status]
style = 'bold #ae81ff'

[hostname]
ssh_symbol = "@"
style = "bold #ffd866"
format = '[$ssh_symbol$hostname]($style):'

[kubernetes]
disabled = false
format = '[\($context\)]($style) '
style = 'bold #ff6188'

[username]
format = "[$user]($style)"
style_user = 'bold #ffd866'
